<?php

namespace Blog\ArticleBundle\Repository;

use Blog\ArticleBundle\Entity\Article;
use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function listArticles($page)
    {
        $query = $this->createQueryBuilder('art')
            ->where('art.statut = :lestatut')
            ->setParameter('lestatut', Article::STATE_PUBLISHED)
            ->orderBy('art.datePublication','DESC')
            ->getQuery();

        $nbResults = Article::NB_PER_PAGE;
        $first = ($page-1)*$nbResults;

        $query->setFirstResult($first);
        $query->setMaxResults($nbResults);

        return $query->getResult();
    }
}
